### ISSUE TITLE
mdPatterns showing plot error

### ISSUE THREAD

**Issue by davzaman** [RianneSchouten/pyampute#20]
```
Unexpected failing examples:
/Users/davina/Documents/Stuff/Code/pyampute/examples/plot_simulation_pipeline.py failed leaving traceback:
Traceback (most recent call last):
  File "/Users/davina/Documents/Stuff/Code/pyampute/examples/plot_simulation_pipeline.py", line 56, in <module>
    patterns = mdp._get_patterns(incompl_data)
AttributeError: 'mdPatterns' object has no attribute '_get_patterns'


/Users/davina/Documents/Stuff/Code/pyampute/examples/plot_easy_example.py failed leaving traceback:
Traceback (most recent call last):
  File "/Users/davina/Documents/Stuff/Code/pyampute/examples/plot_easy_example.py", line 49, in <module>
    patterns = mdp.get_patterns(X_incompl)
  File "/Users/davina/Documents/Stuff/Code/pyampute/pyampute/exploration/md_patterns.py", line 77, in get_patterns
    self._make_plot()
  File "/Users/davina/Documents/Stuff/Code/pyampute/pyampute/exploration/md_patterns.py", line 146, in _make_plot
    ax.imshow(heat_values, aspect="auto", cmap=cmap)
  File "/Users/davina/miniconda3/envs/pymice/lib/python3.9/site-packages/matplotlib/_api/deprecation.py", line 456, in wrapper
    return func(*args, **kwargs)
  File "/Users/davina/miniconda3/envs/pymice/lib/python3.9/site-packages/matplotlib/__init__.py", line 1412, in inner
    return func(ax, *map(sanitize_sequence, args), **kwargs)
  File "/Users/davina/miniconda3/envs/pymice/lib/python3.9/site-packages/matplotlib/axes/_axes.py", line 5442, in imshow
    im.set_data(X)
  File "/Users/davina/miniconda3/envs/pymice/lib/python3.9/site-packages/matplotlib/image.py", line 706, in set_data
    raise TypeError("Image data of dtype {} cannot be converted to "
TypeError: Image data of dtype object cannot be converted to float
```

The first one is an easy fix I think that there's an extra preceding `_` in get_patterns(), but the second one (`TypeError: Image data of dtype object cannot be converted to float
`) is showing up elsewhere as well.

**Comment by RianneSchouten** [comment]
Thank you @davzaman,

The plot_simulation_pipeline has not been finished/updated yet. I hope to do that today or tomorrow.

The plot_easy_example has been updated, but the build files have not been pushed yet. I will do that today. 

Indeed, in the tests, set `show_plot = False`, since mdPatterns makes use of a plt.show() and that won't work within a test. In the future we may want to give the user more options for saving the plot or changing aspects of the plots, etcetera, but for now this should be fine.

**Comment by davzaman** [comment]
I am getting this error outside of testing. If I make a file and run it separately with this contents I get that error:
```python
from pyampute.ampute import MultivariateAmputation
from pyampute.exploration.md_patterns import mdPatterns
import numpy as np

n = 10000
X = np.random.randn(n, 10)
ma = MultivariateAmputation(seed=4)
X_amputed = ma.fit_transform(X)
mdp = mdPatterns()
patterns = mdp.get_patterns(X_amputed, show_plot=True)
```
Error: `Exception has occurred: TypeError Image data of dtype object cannot be converted to float`

**Comment by RianneSchouten** [comment]
@davzaman when I run the exact same code, it works for me. I upgraded my matplotlib to version 3.5.1 and still it works. 

@prabhant how is it for you?

**Comment by davzaman** [comment]
I'm not sure what the issue was but it is resolved by enforcing that heat_values are of type bool. If you're happy with that we can close this issue.

**Comment by RianneSchouten** [comment]
Why did you open this again @davzaman? If you enforce heat_values to be bool, and all unittests pass, then I would be fine with that solution.
