### ISSUE TITLE
Failed tests

### ISSUE THREAD

**Issue by prabhant** [RianneSchouten/pyampute#21]
```
FAIL: test_repeat_pattern (pyampute.tests.test_ampute.TestAmpute) [1 Repeat Pattern on Same Var]
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/prabhant/OpenML/pyampute/pyampute/tests/test_ampute.py", line 134, in test_repeat_pattern
    self.assertTrue(
AssertionError: False is not true

======================================================================
FAIL: test_repeat_pattern (pyampute.tests.test_ampute.TestAmpute) [Repeat Pattern on Same Var, Varying Freq Plus Extra Pattern]
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/prabhant/OpenML/pyampute/pyampute/tests/test_ampute.py", line 154, in test_repeat_pattern
    self.assertTrue(
AssertionError: False is not true

----------------------------------------------------------------------
Ran 26 tests in 0.945s

FAILED (failures=2)
```

**Comment by davzaman** [comment]
Fixed with f903e12, repeat issue as #17
